# Enable all new cops.
AllCops:
  NewCops: enable

# Allow setting of date in gemspec.
Gemspec/DateAssignment:
  Enabled: false

# Do not require multi-factor authentication for RubyGems.
Gemspec/RequireMFA:
  Enabled: false

# Align keys, separators, and values of multi-line hashes.
Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

# Allow extra blank lines.
Layout/EmptyLines:
  Enabled: false

# Allow extra empty line at block body beginning.
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# Allow extra empty line at class body beginning.
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: beginning_only
  Exclude:
    - "lib/pnm/image.rb"

# Allow extra empty line at module body beginning.
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Allow extra spacing.
Layout/ExtraSpacing:
  Enabled: false

# No space before block parameters.
Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

# Allow extra spacing in array literals in test files.
Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - "test/test_*.rb"

# Disable metrics.
Metrics:
  Enabled: false

# Use %Q() instead of %() for string percent literals.
Style/BarePercentLiterals:
  EnforcedStyle: percent_q

# Do not enforce a specific string formatting method.
Style/FormatString:
  Enabled: false

# Allow unnamed format string tokens.
Style/FormatStringToken:
  Enabled: false

# Allow missing frozen string literal comment in Gemfile.
Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile

# Use Ruby 1.9 hash syntax.
# Do not allow the hash value shorthand syntax of Ruby 3.1.
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: never

# Allow parallel assignment.
Style/ParallelAssignment:
  Enabled: false

# Allow redundant assignment before returning.
# (Used here for intention revealing variables.)
Style/RedundantAssignment:
  Exclude:
    - lib/pnm/converter.rb

# Allow %r{} for regular expressions in test files.
# (To avoid ambiguous regexp literal warnings.)
Style/RegexpLiteral:
  Exclude:
    - "test/test_*.rb"

# Use double quotes for string literals.
Style/StringLiterals:
  EnforcedStyle: double_quotes


##### Settings for older Ruby versions #####

# For Ruby <= 2.5.
Gemspec/RequiredRubyVersion:
  Enabled: false

# For Ruby <= 2.3 (no String#unpack1).
# Allow use of unpack(...).first instead of unpack1.
Style/UnpackFirst:
  Enabled: false

# For Ruby <= 2.2 (no frozen string literal).
# Allow non frozen objects assigned to constants.
Style/MutableConstant:
  Enabled: false

# For Ruby <= 2.2 (no Numeric#{positive?,negative?} methods).
# Do not enforce use of numeric predicates.
Style/NumericPredicate:
  Enabled: false

# For Ruby <= 2.0 (include is a private method).
# Allow use of send(:include, ...).
Lint/SendWithMixinArgument:
  Enabled: false
