name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - head
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"
          - "2.6"
          - jruby
        os:
          - ubuntu-latest
          - macos-latest
        include:
          - os: windows-latest
            ruby: "3.2"
          - os: windows-latest
            ruby: "3.1"
          - os: windows-latest
            ruby: "3.0"
          - os: windows-latest
            ruby: jruby

    runs-on: ${{ matrix.os }}

    env:
      BUNDLE_WITHOUT: linter

    steps:
      - name: Dump environment
        run: env | sort
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Dump Ruby version
        run: ruby -v
      - name: Run tests
        run: bundle exec rake test
